import Login from '@/components/Login'
import { SessionProvider } from '@/components/SessionProvider'
import SideBar from '@/components/SideBar'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import '@/styles/globals.css'
import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by Sachin Dilshan',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="flex">
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <>
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>
              <div className="bg-[#343541] flex-1">{children}</div>
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
  
}
